services:
  weather:
    image: fpcloud/weather:latest
    build:
      context: .
    container_name: weather
    environment:
      - FORECAST_PROVIDERS=${FORECAST_PROVIDERS}
    ports:
      - "8050:8000"
    volumes:
      - /Users/rustamkrikbayev/Documents/projects/forecast/config.conf:/app/config.conf:ro
    restart: unless-stopped
